default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  username: trashure
  port: 5432

development:
  <<: *default
  database: trashure_development
  password:

test:
  <<: *default
  database: trashure_test

production:
  <<: *default
  database: trashure_production
  password: <%= ENV["TRASHURE_DATABASE_PASSWORD"] %>
